### ISSUE TITLE
Easy Days discussion

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/easy-days-simulator#1]
@L-M-Sherlock @jakeprobst @user1823 @brishtibheja

According to Jarrett, it's impossible to keep Easy Days percentages at 0: https://github.com/open-spaced-repetition/easy-days-simulator/blob/main/notebook.ipynb

**Comment by L-M-Sherlock** [comment]
And the 50% percentage also doesn't work.

<img width="718" alt="image" src="https://github.com/user-attachments/assets/57758e81-cefb-4f9f-9bc4-35a8d7cf79a1">

**Comment by Expertium** [comment]
I suggest you to add the real percentages per day of the week at the end of the file.

**Comment by L-M-Sherlock** [comment]
What's the baseline of the real percentages? You cannot find out a value corresponding to 100%.

**Comment by brishtibheja** [comment]
> And the 50% percentage also doesn't work.

Can you try without `0%`?

edit: I personally don't see the need for 0 percent here, as it will surely be easy to misuse.

**Comment by brishtibheja** [comment]
> You cannot find out a value corresponding to 100%.

Speaking out of pure intuition, most people would think of it as average daily load in a collection of fairly balanced daily load; here I have no idea.

Note: If such definitions doesn't work for any collection, these numbers will just confuse more people so it'd be +1 for the radio button UI.

**Comment by Expertium** [comment]
~~So based on eyeballing the graphs, it seems like setting the Easy Days percentage to 10% roughly corresponds to the midpoint between 100% and 0%. So setting it to 10% results in half of the maximum possible reduction.
I suggest we use three "radio buttons" as sorata calls them: Normal, Reduced and Minimum. Normal = 100%, Reduced = 10% and Minimum = 0%.~~

![Figure_1](https://github.com/user-attachments/assets/e3843cd9-56b9-4d7b-b997-a1ddb1ca302c)

Maintaining exact percentages is not an option even in theory, since cards with very short intervals aren't fuzzed. So we cannot achieve 0 reviews, as long as cards with intervals of 1-2 days exist. So this seems like our best option.

EDIT: nevermind ,10% is not necessarily the midpoint. Here's another graph.

![Figure_2](https://github.com/user-attachments/assets/2f15832c-4a49-4965-874d-1d616823d5a5)

EDIT 2: I don't know how to do this, honestly. Let's just have 2 buttons - Normal and Minimum, or even a toggle.

**Comment by brishtibheja** [comment]
I am more interested in knowing how a similar graph would look like in a mature collection, e.g. after 100 days.

**Comment by Expertium** [comment]
So, unless someone wants to dig into the math to try and figure out how to make percentages consistent, I propose to make it a binary toggle. Disabled = 100%, enabled = 0%.
And then we can have 7 toggles, one for each day. No clutter.

**Comment by brishtibheja** [comment]
If it's two states we don't need extra buttons so clean. Nobody's confused. I am not against this.

**Comment by jakeprobst** [comment]
couldn't this check if its an interval too low for fuzzing and and check if its on a 0 day and then just +1 the interval? I tried to do this in the notebook but I am failing to probably because I'm doing something dumb.

**Comment by Expertium** [comment]
I'm not sure what you mean. If an interval is too short for fuzzing, we can't modify it.

**Comment by L-M-Sherlock** [comment]
> it a binary toggle. Disabled = 100%, enabled = 0%.

It may induce problem when the user doesn't learn new cards for a while and doesn't forget any cards someday (or the desired retention is so low that the lapsed interval is longer than 2 days. In that case,  0% easy day may break the streak.

**Comment by Expertium** [comment]
> In that case, 0% easy day may break the streak.

Glutanimate will patch that
![image](https://github.com/user-attachments/assets/fdd37f6e-7d83-4cbb-98e2-6f3dc8fa5f62)

**Comment by L-M-Sherlock** [comment]
Good news: I guess I have figured out the method to follow the exact percentages. At least it's better than the previous method:

![image](https://github.com/user-attachments/assets/bde8fe45-a3b4-494f-a262-e9527f227479)

The code:

```python
def check_review_distribution(actual_reviews, percentages):
    total_actual = np.sum(actual_reviews)
    
    expected_distribution = percentages * (total_actual / np.sum(percentages))
    
    comparison = actual_reviews <= expected_distribution
    
    return comparison
```

When the actual percentage is higher than the desired percentage, the date will be masked.

**Comment by brishtibheja** [comment]
what does date being masked mean

**Comment by Expertium** [comment]
Interesting. Then I suppose we could have 3 buttons: Normal (100%), Reduced (50%) and Minimum (0%). Or make it a dropdown menu.

**Comment by L-M-Sherlock** [comment]
> what does date being masked mean

The weight will be set to zero.

**Comment by Expertium** [comment]
@jakeprobst this seems like a good solution, just modify it for the case when all days are masked. If all days are masked - choose the day randomly.
